version: '3.8'
services:
  # Database Services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # Application Services
  app:
    build: .
    container_name: reachinbox-app
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - redis
    command: node dist/index.js

  worker:
    build: .
    container_name: reachinbox-worker
    depends_on:
      - redis
    command: node dist/worker.js